package com.bmv.auditoria.ai.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Auditors;

/**
 * Class _AuditorRoles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditorRoles extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String AUDITORS_ARRAY_PROPERTY = "auditorsArray";

    public static final String ID_AUDITOR_ROLE_PK_COLUMN = "id_auditor_role";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToAuditorsArray(Auditors obj) {
        addToManyTarget("auditorsArray", obj, true);
    }
    public void removeFromAuditorsArray(Auditors obj) {
        removeToManyTarget("auditorsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Auditors> getAuditorsArray() {
        return (List<Auditors>)readProperty("auditorsArray");
    }


}
