package com.bmv.auditoria.ai.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.AuditPhasesTypes;
import com.bmv.auditoria.ai.persistent.Auditors;
import com.bmv.auditoria.ai.persistent.Audits;
import com.bmv.auditoria.ai.persistent.EffortDocuments;
import com.bmv.auditoria.ai.persistent.JobStatus;

/**
 * Class _AuditJobs was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditJobs extends CayenneDataObject {

    public static final String DATE_END_PROPERTY = "dateEnd";
    public static final String DATE_INIT_PROPERTY = "dateInit";
    public static final String EFFORT_DETAIL_PROPERTY = "effortDetail";
    public static final String JOB_DETAIL_PROPERTY = "jobDetail";
    public static final String JOB_NAME_PROPERTY = "jobName";
    public static final String EFFORT_DOCUMENTS_ARRAY_PROPERTY = "effortDocumentsArray";
    public static final String TO_AUDIT_PHASES_TYPES_PROPERTY = "toAuditPhasesTypes";
    public static final String TO_AUDITORS_PROPERTY = "toAuditors";
    public static final String TO_AUDITS_PROPERTY = "toAudits";
    public static final String TO_JOB_STATUS_PROPERTY = "toJobStatus";

    public static final String ID_AUDIT_JOB_PK_COLUMN = "id_audit_job";

    public void setDateEnd(Date dateEnd) {
        writeProperty("dateEnd", dateEnd);
    }
    public Date getDateEnd() {
        return (Date)readProperty("dateEnd");
    }

    public void setDateInit(Date dateInit) {
        writeProperty("dateInit", dateInit);
    }
    public Date getDateInit() {
        return (Date)readProperty("dateInit");
    }

    public void setEffortDetail(String effortDetail) {
        writeProperty("effortDetail", effortDetail);
    }
    public String getEffortDetail() {
        return (String)readProperty("effortDetail");
    }

    public void setJobDetail(String jobDetail) {
        writeProperty("jobDetail", jobDetail);
    }
    public String getJobDetail() {
        return (String)readProperty("jobDetail");
    }

    public void setJobName(String jobName) {
        writeProperty("jobName", jobName);
    }
    public String getJobName() {
        return (String)readProperty("jobName");
    }

    public void addToEffortDocumentsArray(EffortDocuments obj) {
        addToManyTarget("effortDocumentsArray", obj, true);
    }
    public void removeFromEffortDocumentsArray(EffortDocuments obj) {
        removeToManyTarget("effortDocumentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EffortDocuments> getEffortDocumentsArray() {
        return (List<EffortDocuments>)readProperty("effortDocumentsArray");
    }


    public void setToAuditPhasesTypes(AuditPhasesTypes toAuditPhasesTypes) {
        setToOneTarget("toAuditPhasesTypes", toAuditPhasesTypes, true);
    }

    public AuditPhasesTypes getToAuditPhasesTypes() {
        return (AuditPhasesTypes)readProperty("toAuditPhasesTypes");
    }


    public void setToAuditors(Auditors toAuditors) {
        setToOneTarget("toAuditors", toAuditors, true);
    }

    public Auditors getToAuditors() {
        return (Auditors)readProperty("toAuditors");
    }


    public void setToAudits(Audits toAudits) {
        setToOneTarget("toAudits", toAudits, true);
    }

    public Audits getToAudits() {
        return (Audits)readProperty("toAudits");
    }


    public void setToJobStatus(JobStatus toJobStatus) {
        setToOneTarget("toJobStatus", toJobStatus, true);
    }

    public JobStatus getToJobStatus() {
        return (JobStatus)readProperty("toJobStatus");
    }


}
