package com.bmv.auditoria.ai.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.AuditorTeams;
import com.bmv.auditoria.ai.persistent.Auditors;

/**
 * Class _AuditorTeamMembers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditorTeamMembers extends CayenneDataObject {

    public static final String TO_AUDITOR_TEAMS_PROPERTY = "toAuditorTeams";
    public static final String TO_AUDITORS_PROPERTY = "toAuditors";

    public static final String ID_AUDITOR_TEAM_MEMBER_PK_COLUMN = "ID_AUDITOR_TEAM_MEMBER";

    public void setToAuditorTeams(AuditorTeams toAuditorTeams) {
        setToOneTarget("toAuditorTeams", toAuditorTeams, true);
    }

    public AuditorTeams getToAuditorTeams() {
        return (AuditorTeams)readProperty("toAuditorTeams");
    }


    public void setToAuditors(Auditors toAuditors) {
        setToOneTarget("toAuditors", toAuditors, true);
    }

    public Auditors getToAuditors() {
        return (Auditors)readProperty("toAuditors");
    }


}
