package com.bmv.auditoria.ai.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Audits;
import com.bmv.auditoria.ai.persistent.Companies;
import com.bmv.auditoria.ai.persistent.Users;

/**
 * Class _CompanyDepartments was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CompanyDepartments extends CayenneDataObject {

    public static final String DEPARTMENT_PROPERTY = "department";
    public static final String AUDITS_ARRAY_PROPERTY = "auditsArray";
    public static final String TO_COMPANIES_PROPERTY = "toCompanies";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_COMPANY_DEPARTMENT_PK_COLUMN = "id_company_department";

    public void setDepartment(String department) {
        writeProperty("department", department);
    }
    public String getDepartment() {
        return (String)readProperty("department");
    }

    public void addToAuditsArray(Audits obj) {
        addToManyTarget("auditsArray", obj, true);
    }
    public void removeFromAuditsArray(Audits obj) {
        removeToManyTarget("auditsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Audits> getAuditsArray() {
        return (List<Audits>)readProperty("auditsArray");
    }


    public void setToCompanies(Companies toCompanies) {
        setToOneTarget("toCompanies", toCompanies, true);
    }

    public Companies getToCompanies() {
        return (Companies)readProperty("toCompanies");
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget("toUsers", toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty("toUsers");
    }


}
