package com.bmv.auditoria.ai.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.CompanyDepartments;

/**
 * Class _Companies was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Companies extends CayenneDataObject {

    public static final String COMPLETE_NAME_PROPERTY = "completeName";
    public static final String PATH_ICO_PROPERTY = "pathIco";
    public static final String PATH_LOGO_PROPERTY = "pathLogo";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String COMPANY_DEPARTMENTS_ARRAY_PROPERTY = "companyDepartmentsArray";

    public static final String ID_COMPANY_PK_COLUMN = "ID_COMPANY";

    public void setCompleteName(String completeName) {
        writeProperty("completeName", completeName);
    }
    public String getCompleteName() {
        return (String)readProperty("completeName");
    }

    public void setPathIco(String pathIco) {
        writeProperty("pathIco", pathIco);
    }
    public String getPathIco() {
        return (String)readProperty("pathIco");
    }

    public void setPathLogo(String pathLogo) {
        writeProperty("pathLogo", pathLogo);
    }
    public String getPathLogo() {
        return (String)readProperty("pathLogo");
    }

    public void setShortName(String shortName) {
        writeProperty("shortName", shortName);
    }
    public String getShortName() {
        return (String)readProperty("shortName");
    }

    public void addToCompanyDepartmentsArray(CompanyDepartments obj) {
        addToManyTarget("companyDepartmentsArray", obj, true);
    }
    public void removeFromCompanyDepartmentsArray(CompanyDepartments obj) {
        removeToManyTarget("companyDepartmentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CompanyDepartments> getCompanyDepartmentsArray() {
        return (List<CompanyDepartments>)readProperty("companyDepartmentsArray");
    }


}
