package com.bmv.auditoria.ai.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Users;

/**
 * Class _MovementsUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MovementsUser extends CayenneDataObject {

    public static final String DETAIL_PROPERTY = "detail";
    public static final String MOV_DATE_PROPERTY = "movDate";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_MOV_PK_COLUMN = "ID_MOV";

    public void setDetail(String detail) {
        writeProperty("detail", detail);
    }
    public String getDetail() {
        return (String)readProperty("detail");
    }

    public void setMovDate(Date movDate) {
        writeProperty("movDate", movDate);
    }
    public Date getMovDate() {
        return (Date)readProperty("movDate");
    }

    public void setToUsers(Users toUsers) {
        setToOneTarget("toUsers", toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty("toUsers");
    }


}
