package com.bmv.auditoria.ai.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Auditors;
import com.bmv.auditoria.ai.persistent.Audits;
import com.bmv.auditoria.ai.persistent.ObsAuditorComments;
import com.bmv.auditoria.ai.persistent.ObsComplexities;
import com.bmv.auditoria.ai.persistent.ObsFindings;
import com.bmv.auditoria.ai.persistent.ObsImpacts;
import com.bmv.auditoria.ai.persistent.ObsStatus;
import com.bmv.auditoria.ai.persistent.ObsUserComments;
import com.bmv.auditoria.ai.persistent.ObsUsers;
import com.bmv.auditoria.ai.persistent.Users;

/**
 * Class _Observations was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Observations extends CayenneDataObject {

    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String OBSERVATION_PROPERTY = "observation";
    public static final String RECOMMENDATION_PROPERTY = "recommendation";
    public static final String SOLUTION_DATE_PROPERTY = "solutionDate";
    public static final String OBS_AUDITOR_COMMENTS_ARRAY_PROPERTY = "obsAuditorCommentsArray";
    public static final String OBS_USER_COMMENTS_ARRAY_PROPERTY = "obsUserCommentsArray";
    public static final String OBS_USERS_ARRAY_PROPERTY = "obsUsersArray";
    public static final String TO_AUDITORS_PROPERTY = "toAuditors";
    public static final String TO_AUDITS_PROPERTY = "toAudits";
    public static final String TO_OBS_COMPLEXITIES_PROPERTY = "toObsComplexities";
    public static final String TO_OBS_FINDINGS_PROPERTY = "toObsFindings";
    public static final String TO_OBS_IMPACTS_PROPERTY = "toObsImpacts";
    public static final String TO_OBS_STATUS_PROPERTY = "toObsStatus";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_OBSERVATION_PK_COLUMN = "ID_OBSERVATION";

    public void setCreationDate(Date creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty("creationDate");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setObservation(String observation) {
        writeProperty("observation", observation);
    }
    public String getObservation() {
        return (String)readProperty("observation");
    }

    public void setRecommendation(String recommendation) {
        writeProperty("recommendation", recommendation);
    }
    public String getRecommendation() {
        return (String)readProperty("recommendation");
    }

    public void setSolutionDate(Date solutionDate) {
        writeProperty("solutionDate", solutionDate);
    }
    public Date getSolutionDate() {
        return (Date)readProperty("solutionDate");
    }

    public void addToObsAuditorCommentsArray(ObsAuditorComments obj) {
        addToManyTarget("obsAuditorCommentsArray", obj, true);
    }
    public void removeFromObsAuditorCommentsArray(ObsAuditorComments obj) {
        removeToManyTarget("obsAuditorCommentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ObsAuditorComments> getObsAuditorCommentsArray() {
        return (List<ObsAuditorComments>)readProperty("obsAuditorCommentsArray");
    }


    public void addToObsUserCommentsArray(ObsUserComments obj) {
        addToManyTarget("obsUserCommentsArray", obj, true);
    }
    public void removeFromObsUserCommentsArray(ObsUserComments obj) {
        removeToManyTarget("obsUserCommentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ObsUserComments> getObsUserCommentsArray() {
        return (List<ObsUserComments>)readProperty("obsUserCommentsArray");
    }


    public void addToObsUsersArray(ObsUsers obj) {
        addToManyTarget("obsUsersArray", obj, true);
    }
    public void removeFromObsUsersArray(ObsUsers obj) {
        removeToManyTarget("obsUsersArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ObsUsers> getObsUsersArray() {
        return (List<ObsUsers>)readProperty("obsUsersArray");
    }


    public void setToAuditors(Auditors toAuditors) {
        setToOneTarget("toAuditors", toAuditors, true);
    }

    public Auditors getToAuditors() {
        return (Auditors)readProperty("toAuditors");
    }


    public void setToAudits(Audits toAudits) {
        setToOneTarget("toAudits", toAudits, true);
    }

    public Audits getToAudits() {
        return (Audits)readProperty("toAudits");
    }


    public void setToObsComplexities(ObsComplexities toObsComplexities) {
        setToOneTarget("toObsComplexities", toObsComplexities, true);
    }

    public ObsComplexities getToObsComplexities() {
        return (ObsComplexities)readProperty("toObsComplexities");
    }


    public void setToObsFindings(ObsFindings toObsFindings) {
        setToOneTarget("toObsFindings", toObsFindings, true);
    }

    public ObsFindings getToObsFindings() {
        return (ObsFindings)readProperty("toObsFindings");
    }


    public void setToObsImpacts(ObsImpacts toObsImpacts) {
        setToOneTarget("toObsImpacts", toObsImpacts, true);
    }

    public ObsImpacts getToObsImpacts() {
        return (ObsImpacts)readProperty("toObsImpacts");
    }


    public void setToObsStatus(ObsStatus toObsStatus) {
        setToOneTarget("toObsStatus", toObsStatus, true);
    }

    public ObsStatus getToObsStatus() {
        return (ObsStatus)readProperty("toObsStatus");
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget("toUsers", toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty("toUsers");
    }


}
