package com.bmv.auditoria.ai.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Observations;
import com.bmv.auditoria.ai.persistent.Users;

/**
 * Class _ObsUsers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ObsUsers extends CayenneDataObject {

    public static final String CAN_EDIT_PROPERTY = "canEdit";
    public static final String TO_OBSERVATIONS_PROPERTY = "toObservations";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_OBS_USERS_PK_COLUMN = "ID_OBS_USERS";

    public void setCanEdit(Boolean canEdit) {
        writeProperty("canEdit", canEdit);
    }
    public Boolean getCanEdit() {
        return (Boolean)readProperty("canEdit");
    }

    public void setToObservations(Observations toObservations) {
        setToOneTarget("toObservations", toObservations, true);
    }

    public Observations getToObservations() {
        return (Observations)readProperty("toObservations");
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget("toUsers", toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty("toUsers");
    }


}
