package com.bmv.auditoria.ai.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Auditors;
import com.bmv.auditoria.ai.persistent.Audits;
import com.bmv.auditoria.ai.persistent.ReqDocuments;
import com.bmv.auditoria.ai.persistent.RequirementStatus;
import com.bmv.auditoria.ai.persistent.Users;

/**
 * Class _RequirementsInformation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RequirementsInformation extends CayenneDataObject {

    public static final String DATE_DELIVERY_PROPERTY = "dateDelivery";
    public static final String DATE_REQUEST_PROPERTY = "dateRequest";
    public static final String DELIVERY_COMMENT_PROPERTY = "deliveryComment";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String REQ_DOCUMENTS_ARRAY_PROPERTY = "reqDocumentsArray";
    public static final String TO_AUDITORS_PROPERTY = "toAuditors";
    public static final String TO_AUDITS_PROPERTY = "toAudits";
    public static final String TO_REQUIREMENT_STATUS_PROPERTY = "toRequirementStatus";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_REQ_INFO_PK_COLUMN = "id_req_info";

    public void setDateDelivery(Date dateDelivery) {
        writeProperty("dateDelivery", dateDelivery);
    }
    public Date getDateDelivery() {
        return (Date)readProperty("dateDelivery");
    }

    public void setDateRequest(Date dateRequest) {
        writeProperty("dateRequest", dateRequest);
    }
    public Date getDateRequest() {
        return (Date)readProperty("dateRequest");
    }

    public void setDeliveryComment(String deliveryComment) {
        writeProperty("deliveryComment", deliveryComment);
    }
    public String getDeliveryComment() {
        return (String)readProperty("deliveryComment");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToReqDocumentsArray(ReqDocuments obj) {
        addToManyTarget("reqDocumentsArray", obj, true);
    }
    public void removeFromReqDocumentsArray(ReqDocuments obj) {
        removeToManyTarget("reqDocumentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ReqDocuments> getReqDocumentsArray() {
        return (List<ReqDocuments>)readProperty("reqDocumentsArray");
    }


    public void setToAuditors(Auditors toAuditors) {
        setToOneTarget("toAuditors", toAuditors, true);
    }

    public Auditors getToAuditors() {
        return (Auditors)readProperty("toAuditors");
    }


    public void setToAudits(Audits toAudits) {
        setToOneTarget("toAudits", toAudits, true);
    }

    public Audits getToAudits() {
        return (Audits)readProperty("toAudits");
    }


    public void setToRequirementStatus(RequirementStatus toRequirementStatus) {
        setToOneTarget("toRequirementStatus", toRequirementStatus, true);
    }

    public RequirementStatus getToRequirementStatus() {
        return (RequirementStatus)readProperty("toRequirementStatus");
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget("toUsers", toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty("toUsers");
    }


}
