package com.bmv.auditoria.ai.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.RequirementsInformation;

/**
 * Class _RequirementStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RequirementStatus extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String REQUIREMENTS_INFORMATION_ARRAY_PROPERTY = "requirementsInformationArray";

    public static final String ID_REQ_STATUS_PK_COLUMN = "id_req_status";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToRequirementsInformationArray(RequirementsInformation obj) {
        addToManyTarget("requirementsInformationArray", obj, true);
    }
    public void removeFromRequirementsInformationArray(RequirementsInformation obj) {
        removeToManyTarget("requirementsInformationArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RequirementsInformation> getRequirementsInformationArray() {
        return (List<RequirementsInformation>)readProperty("requirementsInformationArray");
    }


}
