package com.bmv.auditoria.ai.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Audits;

/**
 * Class _Subprocesses was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Subprocesses extends CayenneDataObject {

    public static final String SUBPROCESS_DESCRIPTION_PROPERTY = "subprocessDescription";
    public static final String SUBPROCESS_NAME_PROPERTY = "subprocessName";
    public static final String TO_AUDITS_PROPERTY = "toAudits";

    public static final String ID_SUBPROCESS_PK_COLUMN = "ID_SUBPROCESS";

    public void setSubprocessDescription(String subprocessDescription) {
        writeProperty("subprocessDescription", subprocessDescription);
    }
    public String getSubprocessDescription() {
        return (String)readProperty("subprocessDescription");
    }

    public void setSubprocessName(String subprocessName) {
        writeProperty("subprocessName", subprocessName);
    }
    public String getSubprocessName() {
        return (String)readProperty("subprocessName");
    }

    public void setToAudits(Audits toAudits) {
        setToOneTarget("toAudits", toAudits, true);
    }

    public Audits getToAudits() {
        return (Audits)readProperty("toAudits");
    }


}
