package com.bmv.auditoria.ai.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.bmv.auditoria.ai.persistent.Users;

/**
 * Class _UserRoles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserRoles extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String USERS_ARRAY_PROPERTY = "usersArray";

    public static final String ID_USER_ROLE_PK_COLUMN = "id_user_role";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToUsersArray(Users obj) {
        addToManyTarget("usersArray", obj, true);
    }
    public void removeFromUsersArray(Users obj) {
        removeToManyTarget("usersArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Users> getUsersArray() {
        return (List<Users>)readProperty("usersArray");
    }


}
